cacheFolder: ./.yarn/cache

changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**

defaultSemverRangePrefix: ""

compressionLevel: mixed

nodeLinker: pnp

patchFolder: ./.yarn/patches

pnpEnableEsmLoader: true

pnpUnpluggedFolder: ./.yarn/unplugged

preferInteractive: true

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32
