name: 'Setup Redgate Flyway'
description: 'Set up a specific version of Flyway and add the command-line tools to the PATH'
author: 'Redgate'
inputs:
  version:
    description: The version specification
    default: latest
  edition:
    description: The Flyway edition to use. Must be one of 'community', 'teams', or 'enterprise'.
    required: true
  architecture:
    description: The target platform architecture. Defaults to the current platform's architecture.
  platform:
    description: The target OS platform. Defaults to the current platform.
  email:
    description: A Redgate email to be used in conjunction with the token parameter to configure a personal access token (PAT). Used to authenticate Flyway to use either Teams or Enterprise.
    required: false
  token:
    description: A personal access token (PAT) to be used in conjunction with the email configuration parameter. This is used to license Flyway to access Teams or Enterprise features.
    required: false
  i-agree-to-the-eula:
    description: Confirm you consent to the EULA found at https://www.red-gate.com/eula.
    required: true
outputs:
  path:
    description: The path the the tool installation folder
  version:
    description: The specific version installed

runs:
  using: 'node24'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'

branding:
  icon: database
  color: red
